default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: backend_development

test:
  <<: *default
  database: backend_test

production:
  primary: &primary_production
    <<: *default
    database: backend_production
    username: <%= ENV['DATABASE_USERNAME'] %>
    password: <%= ENV["DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: backend_production_cache
    migrations_paths: db/cache_migrate
